# Generated by Django 5.2.5 on 2025-08-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('case_name', models.CharField(blank=True, max_length=255)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('semantic_score', models.FloatField()),
                ('trust_score', models.IntegerField()),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadeddocument')),
            ],
        ),
    ]
