# Generated by Django 5.2.5 on 2025-08-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.verificationreport'),
        ),
    ]
